# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

[workspace]
members = ["authenticode", "authenticode-tool", "xtask"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/google/authenticode-rs"
rust-version = "1.81"
version = "0.4.3-pre.0"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
cms = { version = "0.3.0-pre.0", default-features = false }
der = { version = "0.8.0-rc.6", default-features = false }
digest = { version = "0.11.0-rc.0", default-features = false }
hex = "0.4.3"
object = { version = "0.37.1", default-features = false, features = ["pe", "read_core", "unaligned"] }
sha1 = { version = "0.11.0-rc.0", default-features = false }
sha2 = { version = "0.11.0-rc.0", default-features = false }
x509-cert = "0.3.0-rc.0"

[patch.crates-io]
cms        = { git = "https://github.com/RustCrypto/formats.git" }
der        = { git = "https://github.com/RustCrypto/formats.git" }
pkcs1      = { git = "https://github.com/RustCrypto/formats.git" }
pkcs8      = { git = "https://github.com/RustCrypto/formats.git" }
spki       = { git = "https://github.com/RustCrypto/formats.git" }
x509-cert  = { git = "https://github.com/RustCrypto/formats.git" }

sha1       = { git = "https://github.com/RustCrypto/hashes.git" }
sha2       = { git = "https://github.com/RustCrypto/hashes.git" }

digest     = { git = "https://github.com/RustCrypto/traits.git" }
